version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  invoice-service:
    build: ./invoice-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/invoiceDB
    depends_on:
      - mongo
      - rabbitmq

  email-sender:
    build: ./email-sender
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
